# Generated by Django 5.1.2 on 2024-11-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={},
        ),
        migrations.AlterModelTable(
            name='customerprofile',
            table='CustomerProfile',
        ),
        migrations.AlterModelTable(
            name='sellerprofile',
            table='SellerProfile',
        ),
    ]
