# Generated by Django 5.1.2 on 2024-12-04 14:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('\\d{6}$', 'Enter a valid 6 digit pincode')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customerprofile')),
            ],
        ),
    ]
