# Generated by Django 5.1.2 on 2024-12-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping_address',
            old_name='address_line',
            new_name='address_line1',
        ),
    ]
