# Generated by Django 5.1.2 on 2024-12-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
