# Generated by Django 5.1.2 on 2024-12-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
